refactor(service_mock): set server address from argument
lamoda/gonkey pull request #107
Opened 2021-11-09 19:31 UTC by 33r01b

Привет, хотелось бы управлять адресом поднимаемого мок сервера через аргументы, тк в моем случае тестируемый сервис находится вне сервиса откуда запускаются тесты (другой контейнер) и поэтому мне нужно предопределить адрес мок сервера при старте тестируемого сервиса

2021-11-21 12:45 UTC, What-If-I requested changes

2021-11-21 12:45 UTC, What-If-I commented on mocks/service_mock.go
> +func (m *ServiceMock) StartServer(addr string) error {
Привет. Метод `StartServer` публичный и добавление в него нового параметра сломает обратную совместимость. Хотелось бы этого избежать.
Давай добавим отдельный метод `StartServerWithAddr` или `StartWithAddr` который будет принимать адрес.

2021-11-22 19:40 UTC, 33r01b commented on mocks/service_mock.go
> +func (m *ServiceMock) StartServer(addr string) error {
Да, это решение будет получше, добавил метод StartServerWithAddr

2021-11-23 20:18 UTC, What-If-I approved these changes

2021-11-23 20:57 UTC, merged